apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: google-probe
spec:
  jobName: google-external
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://www.google.com
