---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argo-test-monitor
  namespace: argocd
  labels:
    app.kubernetes.io/instance: test-kube-prometheus-stack-prometheus
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: test-kube-prometheus-stack-prometheus
    prometheus: test-kube-prometheus-stack-prometheus
    release: test
spec:
  namespaceSelector:
    matchNames:
    - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server

  endpoints:
    - port: http
      interval: 15s
