apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argo-test-monitor
  namespace: argocd
  labels:
    release: test  # must match Prometheus serviceMonitorSelector
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server-metrics
  endpoints:
    - port: metrics
      scheme: http
      path: /metrics
      interval: 15s
